pipeline:
  # Build and push tags :
  build-and-push:
    image: plugins/docker
    repo: fpfis/httpd-php
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    tags:
      - ${DRONE_TAG}
      - ${DRONE_TAG%%-*}
      - ${DRONE_BRANCH##*/}
    when:
      event: tag

  # Build and push dev release
  build-and-push-branch:
    image: plugins/docker
    repo: fpfis/httpd-php
    tags: ${DRONE_BRANCH##*/}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: push
      branch: release/*

  # Mark production
  build-and-push-production:
    image: plugins/docker
    repo: fpfis/httpd-php
    tags: production-${DRONE_BRANCH##*/}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: push
      branch: production/*

