version: '2.3'
services:
  web:
    build:
      context: .
      target: httpd-php
      args:
        php_version: 7.1
    environment:
      - SMTP_SERVER=mailhog
      - SMTP_PORT=1025
      - SYSLOG_SERVER_IP=web
      - SYSLOG_SERVER_PORT=514
    ports:
      - 8080:8080
    volumes:
      - ./test:/var/www/html
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025